### ISSUE TITLE
Usage in Angular (17)

### ISSUE THREAD

**Issue by alessiostalla** [mike-lischke/antlr4ng#14]
I can't find a way to use antlr4ng in an Angular app. I get the following:

```
✖ Compiling with Angular sources in Ivy partial compilation mode.
../node_modules/antlr4ng/dist/CharStreams.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~
```

If I set "moduleResolution" to "node16" or "nodenext" everything breaks in the build (it looks like all files are interpreted as CommonJS modules, while they aren't).

I've verified I have no references to `CharStreams` in my code, but it's exported from the "antlr4ng" module (`index.d.ts`).
Would it be possible to make it optional (at least the parts that depend on Node APIs)?

**Comment by alessiostalla** [comment]
PS `CharStreams` is the only class with that declaration and thus, I assume, the only class depending on Node.

**Comment by mike-lischke** [comment]
From what I see you are mixing CJS and ESM, which is why you have this trouble. I don't understand why you have to use that resolution-mode assertion (which is set to "require", which means CommonJS). Instead you should consequently use ESM throughout your project and convert to CJS only in the very last (the build) step - and only if needed.

Check this (large) project, where I use `antlr4ng`: [MySQL Shell GUI](https://github.com/mysql/mysql-shell-plugins/tree/master/gui/frontend). It's a vite (and preact) project using esbuild for the final bundles. So it is comparable to Angular projects.

The use of `node16` requires to have all imports include the file extension, because browsers (where ESM was originally invented) have no search strategy to find a file, like Node.js has. And remove that resolution-mode assertion (I never had a need to use something like that).

I recommend going fully ESM, to avoid all the hassle with mixing module types. Only if you need to run something in VS Code (read: an extension) build to CJS. For Node.js you can still use ESM, by calling it like that:

```
node --experimental-vm-modules <yourscript>
```

or use one of the ESM tools (e.g. ts-node):

```
ts-node-esm: <yourscript>
```

And finally: nothing in antlr4ng requires Node.js, not even CharStreams (which used to in the original code, but I removed the file access code). With a bundler like esbuild dead code (not used imports etc.) would be stripped out, so it's strongly recommended.

**Comment by mike-lischke** [comment]
I just saw that this resolution-mode assertion is in the CharStreams.d.ts file. That was generated automatically, hence I didn't see it before. It probably comes from the use of `Buffer` in the class. Since I almost always use a bundler, this `Buffer` class is usually handled automatically. What if you just remove this assertion from the d.ts file?

**Comment by mike-lischke** [comment]
. o O (I should probably remove the `Buffer` using method)

**Comment by alessiostalla** [comment]
> What if you just remove this assertion from the d.ts file?

I had tried already, and it failed, but I missed a crucial piece – I installed `@types/node` but didn't add "node" to "types" in the right `tsconfig.json` files (Angular has several of those). With that in place, the library builds!

For reference, the error was
```
../node_modules/antlr4ng/dist/CharStreams.d.ts:16:31 - error TS2591: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node` and then add 'node' to the types field in your tsconfig.
```

**Comment by mike-lischke** [comment]
Glad to hear you solved it. Still, I'll remove that method using a Buffer. It's not the task of the runtime to deal with access to resources outside of its realm.
